### ISSUE TITLE
Error on 'Add property '

### ISSUE THREAD

**Issue by TimVanMourik** [gitcoinco/codefund#117]
Hi there!
I just saw Codefund is up and running so I wanted to try it out. Now I'm not completely sure how to use it, but I'm reasonably sure the error is not intended. When I add a property, it gives me back an error. Please have a look at the screenshot of the error, including the console logs:

![error](https://user-images.githubusercontent.com/6152205/38691174-58b9bf4e-3e80-11e8-8553-12b275d513b1.jpg)

**Comment by StareIntoTheBeard** [comment]
@TimVanMourik thanks very much for reporting this. Could you try saving the property with `http://` prepending your url? We definitely need to be reporting a clearer error on this though.

**Comment by TimVanMourik** [comment]
Hi @StareIntoTheBeard , I'm somewhat confused: the url is already prepended with https, right? Or are you referring to a link other than `https://codefund.io/properties`?

**Comment by StareIntoTheBeard** [comment]
Hey @TimVanMourik, sorry I wasn't clear -- I meant the URL in your form (where you've got `www.giraffe.tools`

**Comment by TimVanMourik** [comment]
Yes, got it, it works with `https://www.giraffe.tools`!

**Comment by StareIntoTheBeard** [comment]
👍 Thanks for reporting this, we'll make it more intuitive!

**Comment by TimVanMourik** [comment]
Getting sidetracked here, but just curious: does the ad only work on this domain?

**Comment by StareIntoTheBeard** [comment]
@TimVanMourik Hey, just wanted to let you know we validate the URL fields in the site properly now and should be showing correct errors on the form. I'll close this issue now, thanks again.
