### ISSUE TITLE
Ad Creative Embed Script

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/codefund#36]
API endpoints will be provided. The code needs to do the following:

* Provide a script URL that can be placed on a website
* When the script loads (via browser), an API call is made to the impressions endpoint with browser data
* The html (returned in the payload) will be rendered .. ideally not in iframe, but in the actual HTML inline where the script exists
* If the link is clicked, the user is redirected to the click endpoint (this is likely handled already in the payload)

Extra credit (tip):

* Provide a way for developers to specify in the script (or in js) some attributes of the ad to display (for example, theme (light/dark), width, height, etc.

**Comment by styfle** [comment]
> API endpoints will be provided

Is the endpoint returning JSON or HTML or Markdown?

**Comment by coderberry** [comment]
@styfle this bounty is actually only available to those at the SXSW hackathon.. I'll have lots more though :D

**Comment by styfle** [comment]
@coderberry Sounds fun but I will not be in Texas.
