### ISSUE TITLE
Move Schemas to their contexts

### ISSUE THREAD

**Issue by zacck** [gitcoinco/codefund#58]
# Enhancement
Phoenix 1.3 presents us with a powerful option (Contexts) to use when modelling our application, In lieu of separating a `model` of your application, we would use Contexts to arrange our code and share the functionality. 
More on this see this video https://www.youtube.com/watch?v=tMO28ar0lW8

## Work Proposed 
Move schemas  from `lib/schemas` to their respective contexts

## Done
When we can agree on how to arrange the code

**Comment by coderberry** [comment]
@zacck we just moved the schema files into its own namespace for cleanliness. I don't think moving them back makes sense currently.

**Comment by zacck** [comment]
Seems I based this on the assumption that we were separating the schemas to set the model aside
