### ISSUE TITLE
Fix link to CODE_OF_CONDUCT.md in README.md

### ISSUE THREAD

**Issue by r-frederick** [gitcoinco/codefund#62]
The link to the 'Contributor Code of Conduct' currently links to [https://github.com/codesponsor/web/CODE_OF_CONDUCT.md](https://github.com/codesponsor/web/CODE_OF_CONDUCT.md) which returns a 'Not Found'.

The link should route the user to [https://github.com/gitcoinco/codefund/blob/master/CODE_OF_CONDUCT.md](https://github.com/gitcoinco/codefund/blob/master/CODE_OF_CONDUCT.md)

**Comment by StareIntoTheBeard** [comment]
Thanks @r-frederick!

**Comment by coderberry** [comment]
Fixed
